name = "PCDSampling"
uuid = "dfbb2e35-9de8-4f3a-8f3f-5ff62bf431ae"
version = "0.1.0"
authors = ["Dominik Prossel <dominik.prossel@kit.edu>"]

[workspace]
projects = ["test", "benchmark"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
PCDSamplingCUDAExt = "CUDA"

[compat]
Distributions = "0.25.123"
OhMyThreads = "0.8.5"
julia = "^1.11"
CUDA = "6"
